config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "splash_screen#index"
  resources :categories do
    resources :deals, only: [:new, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :deals, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true

  def recent_deals
    deals.order(created_at: :desc)
  end
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_and_belongs_to_many :categories, dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :deals, foreign_key: :author_id

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  # Only allow a list of trusted parameters through.
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_in_path_for(_resource)
    categories_path
  end

  def after_sign_out_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  # GET /categories
  # GET /categories.json
  def index
    @user = current_user
    @categories = Category.includes(:deals).where(user_id: @user.id)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @deals = @category.deals
  end

  # GET /categories/new
  def new
    @category = Category.new
    @deal_all = Deal.all
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :index, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :index, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def set_categories
    @categories = Category.all
  end

  def category_params
    params.require(:category).permit(:name, :icon, :user_id)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :authenticate_user!
  def index
    @deals = Deal.all
  end

  def new
    @deal = Deal.new
    @category = Category.find(params[:category_id])
  end

  def create
    @category = Category.find(params[:category_id])
    @deal = Deal.new(deal_params)
    if @deal.save
      redirect_to category_path(id: @category.id)
    else
      render :new
    end
  end

  private

  def deal_params
    params.require(:deal).permit(:name, :amount, :author_id, category_ids: [])
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<div class="forms">
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inputs">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="inputs">
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon %>
  </div>
    
  <%= form.hidden_field :user_id, value: current_user.id %>
  
  <div class="save">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/categories/index.html.erb
<div class="categories">
<span class="log-out"><%= link_to 'Logout', destroy_user_session_path, 'data-turbo-method': :delete, class: "logout" %></span>
  <h2>CATEGORIES</h2>

  <!--h3><span>Total amount:</span> <span class="total-sum"> <!%= @user.categories.includes(:deals).map { |category| category.deals.sum(:amount) }.sum %></span></h3-->
  <ul class="categories-list">
  <% @categories.each do |category| %>
    <%= link_to category_path(category) do %>
      <li>
        <img src="<%= category.icon %>" alt="image">
        <div class="category-name">
          <p><%= category.name %></p>
          <sub> <%= category.created_at.strftime("%d %B %Y") %> </sub>
        </div>
        <p class="amount"> <%= number_to_currency(category.deals.sum(:amount)) %> </p>
      </li>
    <% end %>
  <% end %>
  </ul>
</div>
<div class="create-category-link">
  <%= link_to 'Add a new category', new_category_path %>
</div>

app/views/categories/new.html.erb
<h1 class="new-form">New category</h1>

<%= render "form", category: @category %>

<br>

<div class="back">
  <%= link_to "←", categories_path %>
</div>

app/views/categories/show.html.erb
<div class="categories">
  <span class="log-out"><%= link_to 'Logout', destroy_user_session_path, 'data-turbo-method': :delete, class: "logout" %></span>
<h2><span class="go-back"><%= link_to '←', categories_path %></span> TRANSACTIONS</h2>
<h3><span>Total amount:</span><span class="total-sum"> <%= number_to_currency(@category.deals.sum(:amount)) %></span></h3>
<ul>
  <% @category.recent_deals.each do |deal| %>
    <li>
      <div class="category-name">
        <p> <%= deal.name %> </p>
        <sub> <%= deal.created_at.strftime("%d %B %Y") %></sub>
      </div>
      <p class="amount"> <%= number_to_currency(deal.amount) %> </p>
    </li>
  <% end %>
</ul>
</div>
<div class="create-category-link">
  <%= link_to 'Add a new transaction',  new_category_deal_path(category_id: @category.id) %>
</div>

app/views/deals/_form.html.erb
<div class="forms">
<%= form_with(model: deal, url: category_deals_path(@category)) do |form| %>
  <% if deal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this user from being saved:</h2>
 
      <ul>
        <% deal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="inputs">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
 
  <div class="inputs">
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div class="check-boxes">
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name %>
  </div>
    
  <%= form.hidden_field :author_id, value: current_user.id %>
  
  <div class="save">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/deals/new.html.erb
<h1 class="new-form">New transaction</h1>

<%= render "form", deal: @deal %>

<br>

<div class="back">
  <%= link_to "←", category_path(id: @category.id) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.cdnfonts.com/css/proxima-nova-condensed" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <div class="app-container">
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <%= yield %>
    </div>
  </body>
</html>

app/views/splash_screen/index.html.erb
<div class="my-app-name">
  <h1>Budget App</h1>
</div>

<div class="login-and-sign-up">
  <%= link_to 'LOG IN', new_user_session_path, class: "login-link" %>
  <%= link_to 'SIGN UP', new_user_registration_path, class: "sign-up-link" %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>